### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by gcaringal** [ljvmiranda921/ljvmiranda921.github.io#148]
Hey there, I wasn't sure where was the best place to contact you. First of all, congratulations on you work. I've been stalking your github because I want to learn how others in the "biz" use the platform. 

I like your blog, and I want to start one as well. What's your workflow with issues and PRs? What is the idea with using PRs when you can just merge the branch to your master?

I'd love to hear your thoughts on this. I think I've found a mistake in your Readme file, so I want to fork it and send a PR later. Just so I start getting the hang of it.  

Thank you and Mabuhay!

**Comment by ljvmiranda921** [comment]
Hi @gcaringal , I appreciate your message and I'm happy that you've reached out here. This blog feels like a small home that I built 2-3 years ago, and it's nice to see visitors come by!

As for my workflows, it's not as explicitly defined to be honest, but here are my general guidelines:
* **I use the Issues as an Idea Backlog.** Anything that I thought under the sun, I track them in the Issues tab. Things that I may want to write soon, or in the future, gets their own Issue. I also assign "Labels" that denote its progress (icebox, work-in-progress, etc.)
* **I use Pull Requests as a draft for my posts.** I don't write in one burst, given my day-job, I get to produce probably atleast 1-2 blog posts a month. If you'll look into my PRs, there are several commits for one post. I store them in a separate branch first because anything that is in `master` gets published immediately, and I don't want to publish unfinished content :) Once I'm done with the post then I merge them into `master`

Let me know if you have further questions! Also, go ahead and make a PR for the mistake in the Readme file (may I know what is it about first?)

Excited for your blog! Let me know once it's up!

**Comment by gcaringal** [comment]
Hey thanks for your reply. 

> Let me know if you have further questions! Also, go ahead and make a PR for the mistake in the Readme file (may I know what is it about first?)

It's your blog URL. It gives a 404 because it's missing http:// :)

I'll fork it and make a PR :D

**Comment by ljvmiranda921** [comment]
Hey @gcaringal please go ahead!

**Comment by ljvmiranda921** [comment]
Thanks for the PR @gcaringal ! I've already merged it, let me know if you have further questions on blogging :) Share your blog too once you've set that one up!

**Comment by gcaringal** [comment]
@ljvmiranda921 Thanks a bunch! A small step for me but my face was like :D
